// City definitions. Each city is a 6x6 grid of blocks; landmarks occupy one (or 2x2) blocks.
// Names and facts: tr + en (other languages fall back to English).

export const GRID = 6

const L = (id, cell, name, fact, extra = {}) => ({ id, cell, name, fact, size: 1, ry: 0, ...extra })

export const CITIES = [
  {
    id: 'istanbul', flag: '🇹🇷', price: 0,
    name: { en: 'Istanbul', tr: 'İstanbul' },
    time: 'sunset', sky: ['#3d5a9e', '#ffb37a'], fog: '#f2b58e', sun: '#ffc48a', sunPos: [-1, 0.45, -0.7],
    ground: '#9aa36b', style: 'oriental', palette: ['#efe2cc', '#e6c9a8', '#d9b08c', '#f3ead8', '#c98d6a', '#e8d6b0'], roof: '#b5523b', heights: [8, 22],
    trees: 'cypress', sea: 'north', seaColor: '#2a7fb0',
    backdrops: [{ type: 'bosphorusBridge', pos: [80, 0, -420], ry: 0.15 }],
    music: { style: 'turkish', tempo: 96 },
    landmarks: [
      L('hagiaSophia', [1, 3], { en: 'Hagia Sophia', tr: 'Ayasofya' }, { en: 'Completed in 537 AD, it was the largest cathedral in the world for nearly a thousand years.', tr: '537 yılında tamamlanan Ayasofya, yaklaşık bin yıl boyunca dünyanın en büyük katedraliydi.' }),
      L('blueMosque', [3, 4], { en: 'Blue Mosque', tr: 'Sultanahmet Camii' }, { en: 'Built 1609–1616, it is famous for its six minarets and more than 20,000 handmade İznik tiles.', tr: '1609–1616 yılları arasında inşa edildi; altı minaresi ve 20.000’den fazla el yapımı İznik çinisiyle ünlüdür.' }),
      L('galataTower', [4, 1], { en: 'Galata Tower', tr: 'Galata Kulesi' }, { en: 'Built by the Genoese in 1348, it offers a 360° view over the Golden Horn and the Bosphorus.', tr: '1348’de Cenevizliler tarafından yapıldı; Haliç ve Boğaz’a 360° manzara sunar.' }),
      L('maidensTower', [2, 0], { en: "Maiden's Tower", tr: 'Kız Kulesi' }, { en: 'Standing on a tiny islet in the Bosphorus, it has served as a watchtower, lighthouse and café.', tr: 'Boğaz’daki küçük bir adacıkta yer alır; gözetleme kulesi, deniz feneri ve kafe olarak kullanılmıştır.' }),
    ],
  },
  {
    id: 'cappadocia', flag: '🇹🇷', price: 300,
    name: { en: 'Cappadocia', tr: 'Kapadokya' },
    time: 'day', sky: ['#5fa8e8', '#ffe2b8'], fog: '#f0d9b5', sun: '#fff1d6', sunPos: [0.6, 0.7, 0.4],
    ground: '#d6bf94', style: 'rural', palette: ['#e6d2ae', '#dcc49c', '#ead9ba', '#cfb48a'], roof: '#c7a57a', heights: [4, 8],
    trees: 'poplar', sea: null, balloons: true,
    backdrops: [{ type: 'desertDunes', pos: [0, 0, -700] }, { type: 'mountains', pos: [0, 0, 1150], ry: Math.PI }],
    music: { style: 'turkish', tempo: 80 },
    landmarks: [
      L('fairyChimneys', [1, 1], { en: 'Fairy Chimneys', tr: 'Peri Bacaları' }, { en: 'These rock towers formed as soft volcanic tuff eroded away beneath harder basalt caps.', tr: 'Yumuşak volkanik tüf, sert bazalt şapkaların altında aşınarak bu kaya sütunlarını oluşturdu.' }),
      L('uchisar', [4, 2], { en: 'Uçhisar Castle', tr: 'Uçhisar Kalesi' }, { en: 'The highest point in Cappadocia: a giant rock riddled with hundreds of carved rooms.', tr: 'Kapadokya’nın en yüksek noktası; içi yüzlerce oyma odayla dolu dev bir kaya.' }),
      L('goreme', [2, 4], { en: 'Göreme Open Air Museum', tr: 'Göreme Açık Hava Müzesi' }, { en: 'Rock-cut churches with centuries-old frescoes, part of a UNESCO World Heritage Site since 1985.', tr: 'Yüzyıllık fresklerle süslü kaya kiliseleri; 1985’ten beri UNESCO Dünya Mirası.' }),
      L('loveValley', [5, 5], { en: 'Love Valley', tr: 'Aşk Vadisi' }, { en: 'A valley full of tall, slender rock pillars, best seen at sunrise with the balloons.', tr: 'Uzun, ince kaya sütunlarıyla dolu bu vadi en güzel gün doğumunda balonlarla görülür.' }),
    ],
  },
  {
    id: 'paris', flag: '🇫🇷', price: 400,
    name: { en: 'Paris', tr: 'Paris' },
    time: 'sunset', sky: ['#4b5fa8', '#ffb8a0'], fog: '#e8b6a8', sun: '#ffcf9e', sunPos: [0.8, 0.35, -0.5],
    ground: '#7fa05a', style: 'european', palette: ['#efe6d2', '#e6dcc4', '#f2ecdf', '#dcd0b6'], roof: '#5d6872', heights: [14, 22],
    trees: 'round', sea: null,
    backdrops: [{ type: 'hills', pos: [0, 0, -800] }],
    music: { style: 'french', tempo: 150 },
    landmarks: [
      L('eiffel', [2, 2], { en: 'Eiffel Tower', tr: 'Eyfel Kulesi' }, { en: "Built for the 1889 World's Fair, it was only supposed to stand for 20 years.", tr: '1889 Dünya Fuarı için inşa edildi; aslında sadece 20 yıl ayakta kalması planlanmıştı.' }),
      L('arcTriomphe', [4, 4], { en: 'Arc de Triomphe', tr: 'Zafer Takı' }, { en: 'Commissioned by Napoleon in 1806; the Tomb of the Unknown Soldier lies beneath it.', tr: '1806’da Napolyon tarafından yaptırıldı; altında Meçhul Asker Anıtı bulunur.' }),
      L('louvre', [4, 1], { en: 'Louvre', tr: 'Louvre Müzesi' }, { en: "The world's most visited museum and home of the Mona Lisa.", tr: 'Dünyanın en çok ziyaret edilen müzesi ve Mona Lisa’nın evi.' }),
      L('notreDame', [1, 4], { en: 'Notre-Dame', tr: 'Notre-Dame Katedrali' }, { en: 'This Gothic masterpiece was begun in 1163 and reopened in 2024 after the 2019 fire.', tr: '1163’te başlanan bu Gotik şaheser, 2019 yangınının ardından 2024’te yeniden açıldı.' }, { ry: Math.PI / 2 }),
    ],
  },
  {
    id: 'london', flag: '🇬🇧', price: 500,
    name: { en: 'London', tr: 'Londra' },
    time: 'day', sky: ['#7d9cc4', '#dfe6ee'], fog: '#cdd6df', sun: '#fff4e0', sunPos: [0.4, 0.6, 0.6],
    ground: '#6f9a55', style: 'european', palette: ['#b8664a', '#c9b48f', '#a85a44', '#e8e0d0', '#8a4a3a'], roof: '#4c5a63', heights: [10, 24],
    trees: 'round', sea: 'south', seaColor: '#4a6e7e', parked: ['#d6221f'],
    backdrops: [{ type: 'harbourSkyline', pos: [0, 0, 620] }],
    music: { style: 'british', tempo: 112 },
    landmarks: [
      L('bigBen', [1, 2], { en: 'Big Ben', tr: 'Big Ben' }, { en: '“Big Ben” is actually the nickname of the great bell; the tower was renamed Elizabeth Tower in 2012.', tr: '“Big Ben” aslında büyük çanın lakabıdır; kule 2012’de Elizabeth Kulesi adını aldı.' }),
      L('londonEye', [4, 4], { en: 'London Eye', tr: 'London Eye' }, { en: 'This 135 m observation wheel opened in 2000; one rotation takes about 30 minutes.', tr: '135 metrelik bu dönme dolap 2000’de açıldı; bir tur yaklaşık 30 dakika sürer.' }),
      L('towerBridge', [3, 5], { en: 'Tower Bridge', tr: 'Tower Köprüsü' }, { en: 'Opened in 1894, its roadway still lifts to let tall ships pass along the Thames.', tr: '1894’te açıldı; yolu hâlâ Thames’ten geçen büyük gemiler için kalkıyor.' }),
    ],
  },
  {
    id: 'newyork', flag: '🇺🇸', price: 600,
    name: { en: 'New York', tr: 'New York' },
    time: 'night', sky: ['#05081a', '#2a2350'], fog: '#1c1838', sun: '#9fb3ff', sunPos: [-0.3, 0.8, 0.4],
    ground: '#3f5a3a', style: 'modern', palette: ['#8a8f99', '#a9a294', '#6f7480', '#b8b0a0', '#5d6470'], roof: '#444', heights: [30, 80],
    trees: 'round', sea: 'south', seaColor: '#14304a', parked: ['#f7c600'],
    backdrops: [{ type: 'harbourSkyline', pos: [0, 0, -640] }],
    music: { style: 'jazz', tempo: 120 },
    landmarks: [
      L('timesSquare', [3, 2], { en: 'Times Square', tr: 'Times Meydanı' }, { en: 'The New Year’s Eve ball has dropped here since 1907; the billboards never sleep.', tr: 'Yılbaşı topu 1907’den beri burada iner; reklam panoları hiç uyumaz.' }),
      L('empireState', [1, 1], { en: 'Empire State Building', tr: 'Empire State Binası' }, { en: 'Completed in 1931 after just 410 days of construction.', tr: '1931’de sadece 410 günlük inşaatın ardından tamamlandı.' }),
      L('statueLiberty', [4, 5], { en: 'Statue of Liberty', tr: 'Özgürlük Heykeli' }, { en: 'A gift from France, dedicated in 1886 as a symbol of freedom.', tr: 'Fransa’nın hediyesi; 1886’da özgürlüğün sembolü olarak açıldı.' }),
    ],
  },
  {
    id: 'rome', flag: '🇮🇹', price: 700,
    name: { en: 'Rome', tr: 'Roma' },
    time: 'day', sky: ['#4f9ee8', '#fbe8c8'], fog: '#efdcc0', sun: '#fff0d0', sunPos: [0.5, 0.75, 0.3],
    ground: '#8aa05e', style: 'european', palette: ['#e8b77a', '#d98f5c', '#f0d4a4', '#c97a4a', '#efe0c0'], roof: '#b5523b', heights: [10, 18],
    trees: 'pine', sea: null,
    backdrops: [{ type: 'hills', pos: [0, 0, 820], ry: Math.PI }],
    music: { style: 'italian', tempo: 132 },
    landmarks: [
      L('colosseum', [2, 3], { en: 'Colosseum', tr: 'Kolezyum' }, { en: 'Completed in 80 AD, it could hold around 50,000 spectators.', tr: 'MS 80’de tamamlandı ve yaklaşık 50.000 seyirci alabiliyordu.' }),
      L('stPeters', [4, 1], { en: "St. Peter's Basilica", tr: 'Aziz Petrus Bazilikası' }, { en: "Its famous dome was designed by Michelangelo and rises over 130 m.", tr: 'Ünlü kubbesi Michelangelo tarafından tasarlandı ve 130 metreyi aşar.' }, { ry: Math.PI }),
      L('trevi', [1, 0], { en: 'Trevi Fountain', tr: 'Trevi Çeşmesi' }, { en: 'Legend says that throwing a coin over your shoulder means you will return to Rome.', tr: 'Efsaneye göre omzunun üzerinden bozuk para atarsan Roma’ya geri dönersin.' }, { ry: Math.PI }),
    ],
  },
  {
    id: 'athens', flag: '🇬🇷', price: 700,
    name: { en: 'Athens', tr: 'Atina' },
    time: 'day', sky: ['#3f93e6', '#e8f2fb'], fog: '#dce8f2', sun: '#ffffff', sunPos: [-0.4, 0.8, 0.4],
    ground: '#b9a774', style: 'oriental', palette: ['#f4f1ea', '#ece4d4', '#f7f3ec', '#e2d6c0'], roof: '#c96a4a', heights: [6, 14],
    trees: 'olive', sea: 'south', seaColor: '#1f8fc4',
    backdrops: [{ type: 'mountains', pos: [0, 0, -1150] }],
    music: { style: 'greek', tempo: 140 },
    landmarks: [
      L('parthenon', [2, 2], { en: 'Parthenon', tr: 'Parthenon' }, { en: 'Built 447–432 BC on the Acropolis and dedicated to the goddess Athena.', tr: 'MÖ 447–432 yılları arasında Akropolis’te inşa edildi ve tanrıça Athena’ya adandı.' }),
      L('templeZeus', [4, 4], { en: 'Temple of Olympian Zeus', tr: 'Olimpiyalı Zeus Tapınağı' }, { en: 'Begun in the 6th century BC, it was only finished more than 600 years later under Emperor Hadrian.', tr: 'MÖ 6. yüzyılda başlandı; ancak 600 yılı aşkın süre sonra İmparator Hadrian döneminde bitirildi.' }),
      L('panathenaic', [0, 4], { en: 'Panathenaic Stadium', tr: 'Panatinaiko Stadı' }, { en: 'The only stadium in the world built entirely of marble; it hosted the first modern Olympics in 1896.', tr: 'Dünyada tamamen mermerden yapılmış tek stadyum; 1896’da ilk modern olimpiyatlara ev sahipliği yaptı.' }),
    ],
  },
  {
    id: 'tokyo', flag: '🇯🇵', price: 800,
    name: { en: 'Tokyo', tr: 'Tokyo' },
    time: 'night', sky: ['#0a0620', '#3a1d5a'], fog: '#25163f', sun: '#b8a0ff', sunPos: [0.3, 0.8, -0.4],
    ground: '#405a3f', style: 'modern', palette: ['#d9dde3', '#a7b0bb', '#e6e1d8', '#8f99a6', '#c4c9d0'], roof: '#333', heights: [16, 50], neon: true,
    trees: 'sakura', sea: null,
    backdrops: [{ type: 'fuji', pos: [-200, 0, -900] }],
    music: { style: 'japanese', tempo: 110 },
    landmarks: [
      L('tokyoTower', [3, 2], { en: 'Tokyo Tower', tr: 'Tokyo Kulesi' }, { en: 'Inspired by the Eiffel Tower, this 333 m tower opened in 1958.', tr: 'Eyfel Kulesi’nden esinlenen 333 metrelik kule 1958’de açıldı.' }),
      L('sensoji', [1, 4], { en: 'Sensō-ji', tr: 'Sensō-ji Tapınağı' }, { en: "Tokyo's oldest temple, founded in the 7th century; look for the giant red lantern.", tr: 'Tokyo’nun 7. yüzyılda kurulan en eski tapınağı; dev kırmızı fenere dikkat et.' }),
      L('meijiTorii', [5, 0], { en: 'Meiji Shrine', tr: 'Meiji Tapınağı' }, { en: 'Its great wooden torii gate is made of cypress trees over 1,500 years old.', tr: 'Büyük ahşap torii kapısı 1.500 yıldan yaşlı servi ağaçlarından yapılmıştır.' }),
    ],
  },
  {
    id: 'dubai', flag: '🇦🇪', price: 900,
    name: { en: 'Dubai', tr: 'Dubai' },
    time: 'day', sky: ['#4aa3e0', '#f7e4c0'], fog: '#efdcb8', sun: '#fff3d8', sunPos: [0.2, 0.85, 0.5],
    ground: '#dcc28e', style: 'modern', palette: ['#dfe6ea', '#c4d2db', '#e8e1d2', '#9fb6c6', '#f0ece4'], roof: '#ccc', heights: [24, 70],
    trees: 'palm', sea: 'north', seaColor: '#1fa7c9',
    backdrops: [{ type: 'desertDunes', pos: [0, 0, 760] }],
    music: { style: 'arabic', tempo: 100 },
    landmarks: [
      L('burjKhalifa', [3, 3], { en: 'Burj Khalifa', tr: 'Burç Halife' }, { en: 'At 828 m, it has been the tallest building in the world since 2010.', tr: '828 metreyle 2010’dan beri dünyanın en yüksek binası.' }),
      L('burjAlArab', [1, 0], { en: 'Burj Al Arab', tr: 'Burj Al Arab' }, { en: 'Shaped like a ship’s sail, it stands on its own artificial island.', tr: 'Yelken şeklindeki bu otel kendi yapay adasının üzerinde durur.' }),
      L('dubaiFrame', [5, 4], { en: 'Dubai Frame', tr: 'Dubai Çerçevesi' }, { en: 'A 150 m tall picture frame that opened in 2018, linking old and new Dubai.', tr: '2018’de açılan 150 metrelik dev çerçeve, eski ve yeni Dubai’yi birleştirir.' }, { ry: Math.PI / 2 }),
    ],
  },
  {
    id: 'cairo', flag: '🇪🇬', price: 900,
    name: { en: 'Cairo', tr: 'Kahire' },
    time: 'sunset', sky: ['#5a4a8a', '#ffb067'], fog: '#e8a870', sun: '#ffb070', sunPos: [-0.8, 0.3, 0.4],
    ground: '#d6b77e', style: 'desert', palette: ['#e2c89a', '#d6b884', '#ead8b4', '#c9a874'], roof: '#c9a874', heights: [6, 16],
    trees: 'palm', sea: null,
    backdrops: [{ type: 'desertDunes', pos: [0, 0, -720] }, { type: 'desertDunes', pos: [0, 0, 720], ry: Math.PI }],
    music: { style: 'egypt', tempo: 92 },
    landmarks: [
      L('pyramids', [0, 0], { en: 'Pyramids of Giza', tr: 'Gize Piramitleri' }, { en: 'Over 4,500 years old — the only Wonder of the Ancient World still standing.', tr: '4.500 yıldan eski; Antik Dünya’nın Yedi Harikası’ndan ayakta kalan tek eser.' }, { size: 2 }),
      L('sphinx', [3, 1], { en: 'Great Sphinx', tr: 'Büyük Sfenks' }, { en: 'Carved from a single mass of limestone, it is about 73 m long.', tr: 'Tek parça kireç taşından oyulmuştur ve yaklaşık 73 metre uzunluğundadır.' }),
      L('citadelMosque', [4, 4], { en: 'Muhammad Ali Mosque', tr: 'Mehmet Ali Paşa Camii' }, { en: 'Built 1830–1848 in Ottoman style, it crowns the Cairo Citadel.', tr: '1830–1848 yılları arasında Osmanlı tarzında inşa edildi ve Kahire Kalesi’ni taçlandırır.' }),
    ],
  },
  {
    id: 'rio', flag: '🇧🇷', price: 1000,
    name: { en: 'Rio de Janeiro', tr: 'Rio de Janeiro' },
    time: 'day', sky: ['#2f9be8', '#d8f2ff'], fog: '#cfeaf7', sun: '#fffbe8', sunPos: [0.5, 0.8, -0.2],
    ground: '#6fae4e', style: 'latin', palette: ['#f2d16b', '#7fc6e8', '#f29a7a', '#a8e0a0', '#f4f0e6', '#e86a6a'], roof: '#c96a4a', heights: [8, 30],
    trees: 'palm', sea: 'south', seaColor: '#1aa0c8', beach: true,
    backdrops: [{ type: 'sugarloaf', pos: [300, 0, 520] }, { type: 'mountains', pos: [0, 0, -1150] }],
    music: { style: 'samba', tempo: 104 },
    landmarks: [
      L('christRedeemer', [2, 1], { en: 'Christ the Redeemer', tr: 'Kurtarıcı İsa Heykeli' }, { en: 'Completed in 1931, the 30 m statue overlooks the city from Corcovado mountain.', tr: '1931’de tamamlanan 30 metrelik heykel, Corcovado dağından şehre bakar.' }),
      L('maracana', [4, 3], { en: 'Maracanã', tr: 'Maracanã Stadı' }, { en: 'This legendary stadium hosted the World Cup final in both 1950 and 2014.', tr: 'Efsanevi stadyum hem 1950 hem de 2014 Dünya Kupası finallerine ev sahipliği yaptı.' }),
      L('selaron', [1, 4], { en: 'Selarón Steps', tr: 'Selarón Merdivenleri' }, { en: 'Artist Jorge Selarón covered 215 steps with tiles from more than 60 countries.', tr: 'Sanatçı Jorge Selarón 215 basamağı 60’tan fazla ülkeden gelen çinilerle kapladı.' }),
    ],
  },
  {
    id: 'sydney', flag: '🇦🇺', price: 1100,
    name: { en: 'Sydney', tr: 'Sidney' },
    time: 'sunset', sky: ['#2c4f9a', '#ff9e7a'], fog: '#d99a88', sun: '#ffb28a', sunPos: [0.8, 0.3, 0.3],
    ground: '#6e9a4c', style: 'modern', palette: ['#e8e6e0', '#c9d3da', '#d9cbb4', '#a7b6c2'], roof: '#555', heights: [16, 50],
    trees: 'round', sea: 'north', seaColor: '#1f78b4',
    backdrops: [{ type: 'harbourSkyline', pos: [0, 0, 640] }],
    music: { style: 'aussie', tempo: 116 },
    landmarks: [
      L('operaHouse', [2, 0], { en: 'Sydney Opera House', tr: 'Sidney Opera Binası' }, { en: 'Opened in 1973, its shell-like roofs are covered with over a million tiles.', tr: '1973’te açıldı; kabuk biçimli çatıları bir milyondan fazla karoyla kaplıdır.' }),
      L('harbourBridge', [4, 2], { en: 'Harbour Bridge', tr: 'Liman Köprüsü' }, { en: 'Opened in 1932 and nicknamed “the Coathanger” because of its arch.', tr: '1932’de açıldı; kemeri yüzünden “Elbise Askısı” lakabıyla bilinir.' }, { ry: Math.PI / 2 }),
      L('sydneyTower', [2, 4], { en: 'Sydney Tower', tr: 'Sidney Kulesi' }, { en: 'At 309 m, it is the tallest structure in the city.', tr: '309 metreyle şehrin en yüksek yapısıdır.' }),
    ],
  },
  {
    id: 'barcelona', flag: '🇪🇸', price: 1100,
    name: { en: 'Barcelona', tr: 'Barselona' },
    time: 'day', sky: ['#3b9ae6', '#fff0d0'], fog: '#f0e2c8', sun: '#fff2d0', sunPos: [-0.5, 0.7, 0.4],
    ground: '#94a65e', style: 'european', palette: ['#f2dcb8', '#e8c49a', '#f4ece0', '#e0a87a'], roof: '#b5523b', heights: [14, 24],
    trees: 'palm', sea: 'south', seaColor: '#1f90c8', beach: true,
    backdrops: [{ type: 'hills', pos: [0, 0, -820] }],
    music: { style: 'spanish', tempo: 124 },
    landmarks: [
      L('sagrada', [2, 2], { en: 'Sagrada Família', tr: 'Sagrada Família' }, { en: 'Gaudí’s basilica has been under construction since 1882.', tr: 'Gaudí’nin bazilikası 1882’den beri inşa ediliyor.' }),
      L('parkGuell', [4, 0], { en: 'Park Güell', tr: 'Güell Parkı' }, { en: 'Gaudí’s colourful park is famous for its mosaic dragon and wavy benches.', tr: 'Gaudí’nin renkli parkı mozaik ejderhası ve dalgalı banklarıyla ünlüdür.' }),
      L('columbus', [3, 5], { en: 'Columbus Monument', tr: 'Kolomb Anıtı' }, { en: 'Built for the 1888 Universal Exposition, it stands 60 m tall at the port.', tr: '1888 Dünya Fuarı için yapıldı; limanda 60 metre yükseklikte durur.' }),
    ],
  },
  {
    id: 'agra', flag: '🇮🇳', price: 1200,
    name: { en: 'Agra', tr: 'Agra' },
    time: 'sunset', sky: ['#6a5aa8', '#ffc29a'], fog: '#f0b8a0', sun: '#ffc39a', sunPos: [0.7, 0.3, -0.6],
    ground: '#8aa05a', style: 'oriental', palette: ['#e8c9a0', '#d99a6a', '#f2dcc0', '#c9785a', '#f0e6d4'], roof: '#a8473a', heights: [6, 14],
    trees: 'palm', sea: null,
    backdrops: [{ type: 'hills', pos: [0, 0, -820] }],
    music: { style: 'indian', tempo: 90 },
    landmarks: [
      L('tajMahal', [2, 1], { en: 'Taj Mahal', tr: 'Tac Mahal' }, { en: 'Built 1632–1653 by Shah Jahan in memory of his wife Mumtaz Mahal.', tr: 'Şah Cihan tarafından eşi Mümtaz Mahal’in anısına 1632–1653 yılları arasında yaptırıldı.' }, { size: 2, ry: Math.PI }),
      L('agraFort', [4, 4], { en: 'Agra Fort', tr: 'Agra Kalesi' }, { en: 'This red sandstone fortress was the main residence of the Mughal emperors.', tr: 'Bu kırmızı kumtaşı kale, Babür imparatorlarının ana konutuydu.' }),
    ],
  },
  {
    id: 'sanfrancisco', flag: '🇺🇸', price: 1300,
    name: { en: 'San Francisco', tr: 'San Francisco' },
    time: 'day', sky: ['#5f9fdb', '#e8eef2'], fog: '#d8e0e6', sun: '#fff7e8', sunPos: [-0.5, 0.65, 0.5],
    ground: '#6d9a4e', style: 'latin', palette: ['#f2b6c6', '#a8d8e8', '#f6e3a1', '#b8e0b0', '#e8e4dc'], roof: '#5a4e5c', heights: [10, 40],
    trees: 'round', sea: 'north', seaColor: '#2a6f9a',
    backdrops: [{ type: 'goldenGate', pos: [-60, 0, -440], ry: -0.2 }, { type: 'hills', pos: [0, 0, 820], ry: Math.PI }],
    music: { style: 'california', tempo: 128 },
    landmarks: [
      L('transamerica', [3, 3], { en: 'Transamerica Pyramid', tr: 'Transamerica Piramidi' }, { en: 'This 260 m pyramid-shaped skyscraper was completed in 1972.', tr: '260 metrelik piramit biçimli gökdelen 1972’de tamamlandı.' }),
      L('paintedLadies', [1, 4], { en: 'Painted Ladies', tr: 'Painted Ladies' }, { en: 'A famous row of colourful Victorian houses facing Alamo Square park.', tr: 'Alamo Meydanı parkına bakan ünlü renkli Viktorya dönemi evleri.' }),
      L('coitTower', [4, 0], { en: 'Coit Tower', tr: 'Coit Kulesi' }, { en: 'Built in 1933 on Telegraph Hill, with murals painted inside.', tr: '1933’te Telegraph Tepesi’ne inşa edildi; içi duvar resimleriyle süslüdür.' }),
    ],
  },
  {
    id: 'berlin', flag: '🇩🇪', price: 1300,
    name: { en: 'Berlin', tr: 'Berlin' },
    time: 'night', sky: ['#0b1028', '#3a3460'], fog: '#2a2846', sun: '#b0c0ff', sunPos: [0.4, 0.8, 0.3],
    ground: '#4f6a46', style: 'european', palette: ['#c9c2b4', '#e0d8c8', '#b8afa0', '#d8cbb0'], roof: '#4a4f55', heights: [14, 26],
    trees: 'round', sea: null,
    backdrops: [{ type: 'hills', pos: [0, 0, -820] }],
    music: { style: 'techno', tempo: 128 },
    landmarks: [
      L('brandenburg', [2, 3], { en: 'Brandenburg Gate', tr: 'Brandenburg Kapısı' }, { en: 'Built 1788–1791, it became the symbol of German reunification in 1989.', tr: '1788–1791’de yapıldı; 1989’da Almanya’nın birleşmesinin sembolü oldu.' }, { ry: Math.PI / 2 }),
      L('tvTower', [4, 1], { en: 'TV Tower', tr: 'Televizyon Kulesi' }, { en: 'At 368 m, the Fernsehturm is the tallest structure in Germany.', tr: '368 metreyle Fernsehturm Almanya’nın en yüksek yapısıdır.' }),
      L('reichstag', [0, 1], { en: 'Reichstag', tr: 'Reichstag Binası' }, { en: 'Visitors can walk up inside its glass dome, added in 1999.', tr: '1999’da eklenen cam kubbesinde ziyaretçiler yukarı kadar yürüyebilir.' }),
    ],
  },
  {
    id: 'amsterdam', flag: '🇳🇱', price: 1400,
    name: { en: 'Amsterdam', tr: 'Amsterdam' },
    time: 'day', sky: ['#6fa6d8', '#eef3f6'], fog: '#dde6ec', sun: '#fff6e6', sunPos: [0.3, 0.6, 0.7],
    ground: '#6fa44e', style: 'european', palette: ['#6b3a2e', '#8b5a3c', '#a8643f', '#4a3a32', '#e8e0d0'], roof: '#3a3a3a', heights: [10, 18],
    trees: 'round', sea: 'north', seaColor: '#3a6f8a',
    backdrops: [{ type: 'hills', pos: [0, 0, 820], ry: Math.PI }],
    music: { style: 'dutch', tempo: 132 },
    landmarks: [
      L('windmills', [1, 1], { en: 'Zaanse Schans Windmills', tr: 'Zaanse Schans Yel Değirmenleri' }, { en: 'The Netherlands once had around 10,000 windmills pumping water and grinding grain.', tr: 'Hollanda’da bir zamanlar su pompalayan ve tahıl öğüten yaklaşık 10.000 yel değirmeni vardı.' }),
      L('canalHouses', [4, 2], { en: 'Canal Houses', tr: 'Kanal Evleri' }, { en: 'Many have a hook at the top, used to hoist furniture up through the windows.', tr: 'Çoğunun tepesinde eşyaları pencereden yukarı çekmek için kanca vardır.' }),
      L('rijksmuseum', [2, 4], { en: 'Rijksmuseum', tr: 'Rijksmuseum' }, { en: 'Home of Rembrandt’s Night Watch — and cyclists ride right through its passage.', tr: 'Rembrandt’ın Gece Devriyesi’nin evi; bisikletliler içindeki geçitten geçer.' }),
    ],
  },
]

export function cityById(id) {
  return CITIES.find((c) => c.id === id) ?? CITIES[0]
}
